[package]
name = "test-utils"
description = "Key management sample code for testing"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
credibil-ecc.workspace = true
dashmap = "6.1.0"
