
# cargo-vet config file

[cargo-vet]
version = "0.10"

[policy.credibil-core]
audit-as-crates-io = true

[[exemptions.addr2line]]
version = "0.24.2"
criteria = "safe-to-run"

[[exemptions.adler2]]
version = "2.0.1"
criteria = "safe-to-run"

[[exemptions.aead]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.aes]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.aes-gcm]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.aes-kw]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.android_system_properties]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.99"
criteria = "safe-to-deploy"

[[exemptions.arrayref]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.atomic-waker]]
version = "1.1.2"
criteria = "safe-to-run"

[[exemptions.autocfg]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.axum]]
version = "0.8.4"
criteria = "safe-to-run"

[[exemptions.axum-core]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.backtrace]]
version = "0.3.75"
criteria = "safe-to-run"

[[exemptions.base-x]]
version = "0.2.11"
criteria = "safe-to-deploy"

[[exemptions.base16ct]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.22.1"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.9.4"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.19.0"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.10.1"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.36"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.chacha20]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.chacha20poly1305]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.42"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ciborium-io]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ciborium-ll]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.cipher]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.core-foundation-sys]]
version = "0.8.7"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.credibil-core]]
version = "0.1.0@git:b27dc201fea251e6270bc88eac04d74006a9a54f"
criteria = "safe-to-deploy"

[[exemptions.critical-section]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-deploy"

[[exemptions.crunchy]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.crypto-bigint]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.ctr]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "4.1.3"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek-derive]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.dashmap]]
version = "6.1.0"
criteria = "safe-to-deploy"

[[exemptions.data-encoding]]
version = "2.9.0"
criteria = "safe-to-deploy"

[[exemptions.data-encoding-macro]]
version = "0.1.18"
criteria = "safe-to-deploy"

[[exemptions.data-encoding-macro-internal]]
version = "0.1.16"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.10"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.displaydoc]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.ecdsa]]
version = "0.16.9"
criteria = "safe-to-deploy"

[[exemptions.ecies]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.ed25519]]
version = "2.2.3"
criteria = "safe-to-deploy"

[[exemptions.ed25519-dalek]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.elliptic-curve]]
version = "0.13.8"
criteria = "safe-to-deploy"

[[exemptions.ff]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.fiat-crypto]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.find-msvc-tools]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.fnv]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.form_urlencoded]]
version = "1.2.2"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.31"
criteria = "safe-to-run"

[[exemptions.futures-core]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.31"
criteria = "safe-to-run"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-run"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-run"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.ghash]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.31.1"
criteria = "safe-to-run"

[[exemptions.group]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.6.0"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.hkdf]]
version = "0.12.4"
criteria = "safe-to-deploy"

[[exemptions.hmac]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "1.3.1"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.http-body-util]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.http-range-header]]
version = "0.4.2"
criteria = "safe-to-run"

[[exemptions.httparse]]
version = "1.10.1"
criteria = "safe-to-run"

[[exemptions.httpdate]]
version = "1.0.3"
criteria = "safe-to-run"

[[exemptions.hyper]]
version = "1.7.0"
criteria = "safe-to-run"

[[exemptions.hyper-util]]
version = "0.1.16"
criteria = "safe-to-run"

[[exemptions.iana-time-zone]]
version = "0.1.63"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone-haiku]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.icu_collections]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.icu_locale_core]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.icu_normalizer]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.icu_normalizer_data]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.icu_properties]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.icu_properties_data]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.icu_provider]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.idna]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.idna_adapter]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.inout]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.io-uring]]
version = "0.7.10"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.78"
criteria = "safe-to-deploy"

[[exemptions.k256]]
version = "0.13.4"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.175"
criteria = "safe-to-deploy"

[[exemptions.libsecp256k1]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.libsecp256k1-core]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.libsecp256k1-gen-ecmult]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.libsecp256k1-gen-genmult]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.litemap]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.13"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.28"
criteria = "safe-to-deploy"

[[exemptions.matchit]]
version = "0.8.4"
criteria = "safe-to-run"

[[exemptions.memchr]]
version = "2.7.5"
criteria = "safe-to-deploy"

[[exemptions.mime]]
version = "0.3.17"
criteria = "safe-to-run"

[[exemptions.mime_guess]]
version = "2.0.5"
criteria = "safe-to-run"

[[exemptions.miniz_oxide]]
version = "0.8.9"
criteria = "safe-to-run"

[[exemptions.mio]]
version = "1.0.4"
criteria = "safe-to-run"

[[exemptions.multibase]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "8.0.0"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.19"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.7"
criteria = "safe-to-run"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.opaque-debug]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.p256]]
version = "0.13.2"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.4"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.11"
criteria = "safe-to-deploy"

[[exemptions.pem-rfc7468]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.3.2"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-run"

[[exemptions.pkcs8]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.poly1305]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.polyval]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.potential_utf]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.primeorder]]
version = "0.13.6"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.101"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.40"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.17"
criteria = "safe-to-deploy"

[[exemptions.rfc6979]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.26"
criteria = "safe-to-run"

[[exemptions.rustc_version]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.rustversion]]
version = "1.0.22"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.20"
criteria = "safe-to-deploy"

[[exemptions.ryu-js]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.sec1]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.26"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.219"
criteria = "safe-to-deploy"

[[exemptions.serde-jsonlines]]
version = "0.7.0"
criteria = "safe-to-run"

[[exemptions.serde_derive]]
version = "1.0.219"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.143"
criteria = "safe-to-deploy"

[[exemptions.serde_json_canonicalizer]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.serde_path_to_error]]
version = "0.1.17"
criteria = "safe-to-run"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-run"

[[exemptions.sha2]]
version = "0.10.9"
criteria = "safe-to-deploy"

[[exemptions.shlex]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.6"
criteria = "safe-to-run"

[[exemptions.signature]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.11"
criteria = "safe-to-run"

[[exemptions.smallvec]]
version = "1.15.1"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.6.0"
criteria = "safe-to-run"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.6.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.106"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.2"
criteria = "safe-to-run"

[[exemptions.synstructure]]
version = "0.13.2"
criteria = "safe-to-deploy"

[[exemptions.tinystr]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.47.1"
criteria = "safe-to-run"

[[exemptions.tokio-macros]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.tokio-util]]
version = "0.7.16"
criteria = "safe-to-run"

[[exemptions.tower]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.tower-http]]
version = "0.6.6"
criteria = "safe-to-run"

[[exemptions.tower-layer]]
version = "0.3.3"
criteria = "safe-to-run"

[[exemptions.tower-service]]
version = "0.3.3"
criteria = "safe-to-run"

[[exemptions.tracing]]
version = "0.1.41"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.30"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.34"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.unicase]]
version = "2.8.1"
criteria = "safe-to-run"

[[exemptions.unicode-ident]]
version = "1.0.18"
criteria = "safe-to-deploy"

[[exemptions.universal-hash]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.url]]
version = "2.5.7"
criteria = "safe-to-deploy"

[[exemptions.utf8_iter]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.18.1"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.1+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.14.4+wasi-0.2.4"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.101"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.101"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.101"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.101"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.101"
criteria = "safe-to-deploy"

[[exemptions.windows-core]]
version = "0.61.2"
criteria = "safe-to-deploy"

[[exemptions.windows-implement]]
version = "0.60.0"
criteria = "safe-to-deploy"

[[exemptions.windows-interface]]
version = "0.59.1"
criteria = "safe-to-deploy"

[[exemptions.windows-link]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.windows-link]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.windows-result]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.windows-strings]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.wit-bindgen]]
version = "0.45.1"
criteria = "safe-to-deploy"

[[exemptions.writeable]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.x25519-dalek]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.yoke]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.yoke-derive]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zerofrom]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.zerofrom-derive]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.zeroize_derive]]
version = "1.4.2"
criteria = "safe-to-deploy"

[[exemptions.zerotrie]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.zerovec]]
version = "0.11.4"
criteria = "safe-to-deploy"

[[exemptions.zerovec-derive]]
version = "0.11.1"
criteria = "safe-to-deploy"
