[package]
name = "credibil-jose"
description = "Credibil information security utilities for Javascript Object Signing and Encryption (JOSE) and JSON Web Tokens (JWT)."
license.workspace = true
readme = "README.md"
authors.workspace = true
categories.workspace = true
edition.workspace = true
exclude = [".*", "snapshots/"]
homepage.workspace = true
keywords.workspace = true
repository.workspace = true
rust-version.workspace = true
version = "0.1.2"

[lib]
# crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
anyhow = "1.0.98"
base64ct.workspace = true
credibil-se.workspace = true
multibase.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_repr.workspace = true
tracing.workspace = true
zeroize.workspace = true

[dev-dependencies]
hex = "0.4.3"
tokio.workspace = true
# test-kms = { path = "../ose/crates/test-kms" }
test-kms.workspace = true
