name: Verify

on:
  push:
    # paths:
    #   - '**/src/**'
    #   - '**/tests/**'
    

jobs:
  verify:
    uses: credibil/pipeline/.github/workflows/verify.yaml@main
    with:
      outdated: rand
